### ISSUE TITLE
Wrapping unrecoverable error makes it impossible to detect

### ISSUE THREAD

**Issue by Nitjsefni7** [avast/retry-go#72]
When wrapping error already wrapped with `retry.Unrevocerable()` it is not going to be properly detected by `retry.IsRecoverable()`.

Example:
```
package main

import (
	"errors"
	"fmt"

	"github.com/avast/retry-go/v4"
)

func main() {
     err := retry.Unrecoverable(errors.New("unrecoverable err"))
     errWr := fmt.Errorf("wrapping: %w", err)

     // This is going to be printed.
     if !retry.IsRecoverable(err) {
          fmt.Println("unrecoverable")
     }

     // This is not going to be printed.
     if !retry.IsRecoverable(errWr) {
          fmt.Println("wrapped unrecoverable")
     }
}
```

Suggestion - while checking if error is recoverable, continue to unwrap error if possible:
```
// IsRecoverable checks if error is an instance of `unrecoverableError`
func IsRecoverable(err error) bool {
	for {
		if _, isUnrecoverable := err.(unrecoverableError); isUnrecoverable {
			return false
		}

		if err = errors.Unwrap(err); err == nil {
			return true
		}
	}
}
```

**Comment by JaSei** [comment]
This should be fixed by 4.3.2 properly - can you please check it? Thanks

**Comment by jamescostian** [comment]
@JaSei it's still broken - the issue is [this code](https://github.com/avast/retry-go/blob/v4.3.2/retry.go#L280-L284), which should be replaced with:

```go
// IsRecoverable checks if error is an instance of `unrecoverableError`
func IsRecoverable(err error) bool {
	return !errors.Is(err, unrecoverableError{})
}

// Adds support for errors.Is usage on unrecoverableError
func (unrecoverableError) Is(err error) bool {
	_, isUnrecoverable := err.(unrecoverableError)
	return isUnrecoverable
}
```

This way, go will be able to continuously call `.Unwrap` on errors to find the real error, and on the `unrecoverableError`, it can call the `Is` method to see that it is indeed an `unrecoverableError`.

To see this in action, compare [the updated code](https://go.dev/play/p/I_F7pPLbDva) to [the existing code](https://go.dev/play/p/QfdYOgv_J_8).
